Dpalazzari/johari_window_api

- app/models/adjective.rb
- app/models/assignment.rb
- app/models/description.rb
- app/models/user.rb
- db/migrate/20170327225029_create_users.rb
- db/migrate/20170327225259_create_adjectives.rb
- db/migrate/20170327225409_create_descriptions.rb
- db/migrate/20170327225517_create_assignments.rb
- db/migrate/20170327232055_add_adjective_to_description.rb
- db/schema.rb
- spec/factories/adjectives.rb
- spec/factories/assignments.rb
- spec/factories/descriptions.rb
- spec/factories/users.rb
- spec/models/adjective_spec.rb
- spec/models/assignment_spec.rb
- spec/models/description_spec.rb
- spec/models/user_spec.rb
In this PR:
- Creates User Model
- Adds User model relationships
- Adds User model relationships tests
- Creates Adjective model
- Adds adjective model relationships
- Adds adjective model relationship tests
- Creates assignment model
- Adds assignment model relationships
- adds assignment model relationships tests
- Creates description model
- Adds description model relationships
- Adds description model relationships tests
Worked on the branch with @wlffann 
Our database schema is one of a kind, so we need @kheppenstall @lucyconklin @akintner to closely read, and make sure you understand the relationships. 
Feedback/requests for changes are expected.
FYI @case-eee
> Making models

- .travis.yml
> Adds travis.yml file

- app/controllers/api/v1/base_controller.rb
This PR sets the CORS accessibility for the API.
@Dpalazzari @wlffann @case-eee
> Cors headers

- db/seeds.rb
In this PR:
- Adds seed data for adjectives to db.
Only needs one review @lucyconklin
> Add adjectives to  seed file

- Gemfile
- Gemfile.lock
- app/controllers/api/v1/adjectives_controller.rb
- app/controllers/api/v1/base_controller.rb
- config/routes.rb
- spec/api/v1/adjectives/adjectives_request_spec.rb
- spec/factories/adjectives.rb
Adds adjective endpoint test, route, controller, and adjective factory.
All tests pass.
FYI @case-eee @lucyconklin @kheppenstall @akintner
> Adjectives Endpoint

- db/seeds.rb
This updates the seed file to create users and assign some other users
to them to be described.
[#142649211]
> Add seed file for users and assignments

- Gemfile
- README.md
- adds link to adjectives endpoint on localhost
- adds some more detail for API endpoints
- also removes duplicate Faker gem in Gemfile
> Updates README.md

- app/controllers/api/v1/users/descriptions_controller.rb
- app/models/assignment.rb
- app/models/user.rb
- config/routes.rb
- spec/models/assignment_spec.rb
- spec/models/user_spec.rb
- spec/requests/api/v1/users/user_descriptions_spec.rb
In this PR:
- adds ability to POST to /api/v1/users/:id/descriptions
- Adds request test for Post
- Adds model tests
- All tests pass
[#142558933]
FYI @case-eee
> 142558933 post johari aw dp

- app/controllers/api/v1/users/users_controller.rb
- config/routes.rb
- spec/requests/api/v1/users/request_spec.rb
In this PR:
- Adds individual user API endpoint
- Adds test for user endpoint API
[#142745339]
FYI @case-eee
> Add user show endpoint and test

- app/controllers/api/v1/base_controller.rb
In order to more fully allow the React App access, I have updated the CORS headers to include the following: 
-  add     headers['Access-Control-Request-Method'] = '*'
- update     headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization, Token'
> update CORS access control headers

- Gemfile
- Gemfile.lock
- app/controllers/home_controller.rb
- config/routes.rb
- spec/features/user_visits_root_path_spec.rb
Uses redcarpet gem to parse README file and render it as the API splash
page.
[#142727413]
FYI @case-eee
> Adds cool splash page

- app/controllers/api/v1/users/descriptions_controller.rb
- app/models/assignment.rb
- spec/requests/api/v1/users/user_descriptions_spec.rb
This PR checks the assignment and makes sure it isn’t already true.
[#142745305]
> Check assignment

- app/models/johari.rb
- spec/factories/descriptions.rb
- spec/models/johari_spec.rb
-Refactor how frequencies are calculated in johari pr.
-Add tests for johari PORO.
@Dpalazzari @akintner @lucyconklin @wlffann Ready for review. Let's all review and comment on this one since its pretty big.
@case-eee FYI
> 142737153 kh johari poro tests

- Gemfile
- app/controllers/api/v1/base_controller.rb
- app/controllers/api/v1/users/descriptions_controller.rb
- app/models/johari.rb
- config/application.rb
- spec/factories/descriptions.rb
- spec/models/johari_spec.rb
- spec/requests/api/v1/users/user_descriptions_spec.rb
-Remove cors methods in base controller
-Add rack-cors gem
-Update application.rb for rack-cors gem
> 142812229 dp kh cors headers for post

- config/application.rb
- config/initializers/cors.rb
Change where cors configuration occurs in rails api project.
@lucyconklin @wlffann @Dpalazzari @akintner Just needs one review.
> Move cors middleware config

- db/seeds.rb
In this PR: 
- updates adjective list to Allison's new list. 
RIP Religious 🥇 
Need one person to merge @lucyconklin @wlffann @akintner 
Note, this will change the JSON on our API, and probably some things we've done on the front end, once it is in production.
> Update adjectives lists

- README.md
- app/controllers/api/v1/assignments_controller.rb
- app/models/assignment_creator.rb
- config/routes.rb
- spec/factories/users.rb
- spec/requests/api/v1/assignments/post_spec.rb
- spec/support/request_helper.rb
Worked with @Dpalazzari to Add endpoint `api/v1/assignments`.
* `AssignmentCreator` poro handles the logic of taking in groups and making assignments.
* Readme.md updated with the endpoint information so front-end team can format the ajax call to match the endpoint.
@lucyconklin @wlffann @akintner Ready for review. Needs one reviewer.
@case-eee FYI
> 142812011 kh create assignments

- README.md
- app/controllers/api/v1/cohorts/users_controller.rb
- app/controllers/api/v1/cohorts_controller.rb
- app/models/cohort.rb
- app/models/user.rb
- config/routes.rb
- db/migrate/20170405215456_create_cohorts.rb
- db/migrate/20170405222047_add_cohort_to_user.rb
- db/schema.rb
- spec/factories/cohorts.rb
- spec/factories/users.rb
- spec/models/cohort_spec.rb
- spec/models/user_spec.rb
- spec/requests/api/v1/cohorts/request_spec.rb
- spec/requests/api/v1/cohorts/user_request_spec.rb
Worked on this PR with @kheppenstall :
- Adds two cohort endpoints: one by cohort and one that returns a cohorts users
- All tests pass
- Readme updated
Probably needs one person to review. @lucyconklin @akintner @wlffann 
[#142811879] [#142811863]
FYI @case-eee
> cohorts endpoints

- README.md
- app/controllers/api/v1/users_controller.rb
- app/models/user.rb
- config/routes.rb
- db/migrate/20170405234109_add_attributes_to_user.rb
- db/schema.rb
- spec/factories/users.rb
- spec/models/user_spec.rb
- spec/requests/api/v1/users/request_spec.rb
- Adds a post request to our users endpoint.
- Adds token and github attributes to user model
- Post requests to this endpoint REQUIRES a token/github login
- Updates factories
- All tests pass
[#142992579]
Needs one person to review @lucyconklin @wlffann @akintner 
FYI @case-eee
> Post /users endpoint

- db/seeds.rb
- Alters seeded users
- Adds seeded cohorts
- Adds seeded descriptions
[#143217223]
Needs one reviewer @lucyconklin @wlffann @akintner 
FYI @case-eee
> Update Seed file

- app/controllers/api/v1/users_controller.rb
- spec/requests/api/v1/users/request_spec.rb
- updates post to users with strong params
- rewrites tests
> Add strong params and search feature

- .gitignore
- Gemfile
- Gemfile.lock
- README.md
- app/controllers/api/v1/users_controller.rb
- app/models/user.rb
- app/services/census_service.rb
- config/application.sample.yml
- spec/factories/users.rb
- spec/fixtures/vcr_cassettes/census/service_get_cohort_by_github_returns_cohort_name.yml
- spec/fixtures/vcr_cassettes/census/service_get_token_returns_an_access_token.yml
- spec/fixtures/vcr_cassettes/user/endpoint_post_/users_saves_the_user_to_our_database.yml
- spec/fixtures/vcr_cassettes/user/methods_add_cohort.yml
- spec/models/user_spec.rb
- spec/rails_helper.rb
- spec/requests/api/v1/users/request_spec.rb
- spec/services/census_spec.rb
-Add a census service
-Census service method `.get_token` to retrieve an api token from census
-Census service method `.get_cohort_by_github` to retrieve user's cohort from github username
-Add `#add_cohort` to user that find or creates a cohort by cohort name
-Call `#add_cohort` after saving in the `POST to /users`
@lucyconklin @wlffann Ready for review. You will need three environment variables. Check slack.
FYI: Please do not delete the VCRs for now because that will change the `CENSUS_TOKEN` env variable that we all have to have in our `application.yml`. This will no longer be a problem once we have the rake task up and running.
@case-eee FYI
Worked with @Dpalazzari
> 143191085 kh dp integrate with census

- app/models/johari.rb
- spec/models/johari_spec.rb
-Edit frequency calculation in window
-Pull adj_per_johari out into a method
-Edit frequencies in tests to match new calculation after dividing by
15 instead of 10
@Dpalazzari @lucyconklin @wlffann Only needs one review.
@case-eee FYI
> Edit johari from 10 adj to 15 adj

- app/controllers/api/v1/users_controller.rb
- app/models/user.rb
- app/services/census_service.rb
- db/migrate/20170412220847_add_role_to_users.rb
- db/schema.rb
- lib/tasks/census.rake
- spec/fixtures/vcr_cassettes/census/service_get_data_by_github_returns_cohort_name.yml
- spec/fixtures/vcr_cassettes/census/service_get_data_by_github_returns_roles_for_staff.yml
- spec/fixtures/vcr_cassettes/census/service_get_data_by_github_returns_roles_for_student.yml
- spec/fixtures/vcr_cassettes/user/endpoint_post_/users_saves_the_user_to_our_database.yml
- spec/fixtures/vcr_cassettes/user/methods_add_cohort_and_role_adds_for_cohort_and_role_for_staff_based_on_census_data.yml
- spec/fixtures/vcr_cassettes/user/methods_add_cohort_and_role_adds_for_student_based_on_census_data.yml
- spec/fixtures/vcr_cassettes/user/methods_add_cohort_and_role_adds_for_user_without_census_login_based_on_census_data.yml
- spec/models/user_spec.rb
- spec/requests/api/v1/users/request_spec.rb
- spec/services/census_spec.rb
-Add enum for `role` on user that can be 'student' (0) or 'staff' (1)
-Update `CensusService` to retrieve role and cohort data
-Update `UsersController` to add cohort and role after save
-Update `User` model to have `add_cohort_and_role` method that adds them appropriately based on the data retrieved from the `CensusService`
-Update rake task to update cohort and role (task is now `rake census:update`)
@Dpalazzari @wlffann @lucyconklin This is a bigger one so maybe two reviewers.
@case-eee FYI
> 143595731 kh user roles
